{
 "title": "33901 Dashboard Big",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cistern",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cistern_level",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "options": {
    "content": "<iframe src=\"https://forecast.io/embed/#lat=39.883935&lon=-105.3867463&name=Coal%20Creek%20Canyon&color=#ffffff&text-color=#ffffff&font=Helvetica&units=us\" width=\"100%\" height=\"100%\"</iframe>"
   },
   "content": "<img src=\"http://iris.33901.cloud:81/image/DF\" style=\"max-height:100%\" id=\"DF\" />\n<script type=\"text/javascript\">\nsetInterval(function(){var myimg = document.getElementById(\"DF\"); myimg.src = \"http://iris.33901.cloud:81/image/DF?\"+new Date().getTime()},2000);\n</script>"
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "windSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "options": {
    "content": "<iframe id=\"darksky\" width=\"100%\" height=\"100%\" src=\"https://embed.windy.com/embed2.html?lat=39.780&lon=-105.349&detailLat=39.780&detailLon=-105.349&width=650&height=450&zoom=10&level=surface&overlay=radar&product=radar&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1\" frameborder=\"0\"></iframe>\n<script type=\"text/javascript\">\nsetInterval(function(){document.getElementById('darksky').contentWindow.location.reload();}, 900000);\n</script>\n\n"
   },
   "content": "<img src=\"http://iris.33901.cloud:81/image/DF\" style=\"max-height:100%\" id=\"DF\" />\n<script type=\"text/javascript\">\nsetInterval(function(){var myimg = document.getElementById(\"DF\"); myimg.src = \"http://iris.33901.cloud:81/image/DF?\"+new Date().getTime()},2000);\n</script>"
  },
  {
   "title": "Today",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather_forecast",
     "query": "SELECT last(\"today\") FROM \"weather_forecast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tomorrow",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather_forecast",
     "query": "SELECT last(\"tomorrow\") FROM \"weather_forecast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mountain Broadband",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mtnbb_traffic",
     "query": "SELECT derivative(last(\"out\"), 1s)*8 as d FROM \"mtnbb_fiber\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(last(\"in\"), 1s)*8 FROM \"mtnbb_fiber\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Starlink",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mtnbb_traffic",
     "query": "SELECT derivative(last(\"out\"), 1s)*8 as d FROM \"starlink_bandwidth\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(last(\"in\"), 1s)*8 FROM \"starlink_bandwidth\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BTC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cryptocurrency",
     "select": [
      [
       { "params": [ "USDT_BTC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Crypto",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "crypto_balance",
     "select": [
      [
       { "params": [ "usd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Mining Profitability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "USD" }
   ],
   "targets": [
    {
     "alias": "Real Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nicehash",
     "select": [
      [
       { "params": [ "per_month_profitability" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Moving Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nicehash",
     "select": [
      [
       { "params": [ "per_month_profitability" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "75" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ETH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cryptocurrency",
     "select": [
      [
       { "params": [ "USDT_ETH" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}